import 'song.dart';
import 'video.dart';

/// The type of media a playlist can hold.
enum PlaylistMedia { music, video, mixed }

class Playlist {
  final int? id;
  final String name;
  final DateTime createdAt;
  List<Song> songs;
  List<Video> videos;
  String? description;
  bool isAutoGenerated;
  PlaylistMedia mediaType;

  Playlist({
    this.id,
    required this.name,
    DateTime? createdAt,
    List<Song>? songs,
    List<Video>? videos,
    this.description,
    this.isAutoGenerated = false,
    this.mediaType = PlaylistMedia.music,
  })  : createdAt = createdAt ?? DateTime.now(),
        songs = songs ?? [],
        videos = videos ?? [];

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'created_at': createdAt.toIso8601String(),
      'description': description,
      'is_auto_generated': isAutoGenerated ? 1 : 0,
      'media_type': mediaType.name,
    };
  }

  factory Playlist.fromMap(Map<String, dynamic> map) {
    final mediaName = map['media_type'] ?? 'music';
    return Playlist(
      id: map['id'],
      name: map['name'] ?? 'Unnamed Playlist',
      createdAt: map['created_at'] != null
          ? DateTime.tryParse(map['created_at']) ?? DateTime.now()
          : DateTime.now(),
      description: map['description'],
      isAutoGenerated: map['is_auto_generated'] == 1,
      mediaType: PlaylistMedia.values
          .where((m) => m.name == mediaName)
          .firstOrNull ??
          PlaylistMedia.music,
    );
  }

  int get totalItems => songs.length + videos.length;

  String get itemCountLabel {
    if (mediaType == PlaylistMedia.video) {
      return '${videos.length} video${videos.length != 1 ? 's' : ''}';
    }
    if (mediaType == PlaylistMedia.mixed) {
      return '${songs.length} track${songs.length != 1 ? 's' : ''} · '
          '${videos.length} video${videos.length != 1 ? 's' : ''}';
    }
    return '${songs.length} song${songs.length != 1 ? 's' : ''}';
  }

  Duration get totalDuration {
    final songSeconds = songs.fold<int>(0, (sum, s) => sum + s.duration);
    final videoSeconds = videos.fold<int>(0, (sum, v) => sum + v.duration);
    return Duration(seconds: songSeconds + videoSeconds);
  }

  String get formattedDuration {
    final d = totalDuration;
    if (d.inHours > 0) {
      return '${d.inHours}h ${d.inMinutes.remainder(60)}m';
    }
    return '${d.inMinutes}m';
  }
}

