import 'song.dart';

class Playlist {
  final int? id;
  final String name;
  final DateTime createdAt;
  List<Song> songs;
  String? description;
  bool isAutoGenerated;

  Playlist({
    this.id,
    required this.name,
    DateTime? createdAt,
    List<Song>? songs,
    this.description,
    this.isAutoGenerated = false,
  })  : createdAt = createdAt ?? DateTime.now(),
        songs = songs ?? [];

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'created_at': createdAt.toIso8601String(),
      'description': description,
      'is_auto_generated': isAutoGenerated ? 1 : 0,
    };
  }

  factory Playlist.fromMap(Map<String, dynamic> map) {
    return Playlist(
      id: map['id'],
      name: map['name'] ?? 'Unnamed Playlist',
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'])
          : DateTime.now(),
      description: map['description'],
      isAutoGenerated: map['is_auto_generated'] == 1,
    );
  }

  Playlist copyWith({
    int? id,
    String? name,
    DateTime? createdAt,
    List<Song>? songs,
    String? description,
    bool? isAutoGenerated,
  }) {
    return Playlist(
      id: id ?? this.id,
      name: name ?? this.name,
      createdAt: createdAt ?? this.createdAt,
      songs: songs ?? this.songs,
      description: description ?? this.description,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }

  String get songCount => '${songs.length} song${songs.length != 1 ? 's' : ''}';

  Duration get totalDuration {
    final totalSeconds = songs.fold<int>(0, (sum, s) => sum + s.duration);
    return Duration(seconds: totalSeconds);
  }

  String get formattedDuration {
    final d = totalDuration;
    if (d.inHours > 0) {
      return '${d.inHours}h ${d.inMinutes.remainder(60)}m';
    }
    return '${d.inMinutes}m';
  }
}
