import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/music_provider.dart';
import '../models/playlist.dart';
import '../models/song.dart';
import '../theme/app_theme.dart';
import '../widgets/common_widgets.dart';
import 'now_playing_screen.dart';

class PlaylistScreen extends StatelessWidget {
  const PlaylistScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.primaryDark,
      appBar: AppBar(
        title: const Text('Playlists'),
        actions: [
          IconButton(
            icon: const Icon(Icons.auto_fix_high_rounded),
            tooltip: 'Generate Smart Playlists',
            onPressed: () async {
              await context.read<MusicProvider>().generateAutoPlaylists();
              if (context.mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Smart playlists updated!'),
                    backgroundColor: AppTheme.accentTertiary,
                    behavior: SnackBarBehavior.floating,
                  ),
                );
              }
            },
          ),
        ],
      ),
      body: Consumer<MusicProvider>(
        builder: (context, provider, _) {
          if (provider.isLoading) {
            return const Center(
                child: CircularProgressIndicator(color: AppTheme.accent));
          }

          final auto =
              provider.playlists.where((p) => p.isAutoGenerated).toList();
          final manual =
              provider.playlists.where((p) => !p.isAutoGenerated).toList();

          if (provider.playlists.isEmpty) {
            return _buildEmptyState(context, provider);
          }

          return ListView(
            padding: const EdgeInsets.fromLTRB(16, 8, 16, 120),
            children: [
              if (auto.isNotEmpty) ...[
                _sectionHeader('Smart Playlists', '${auto.length} playlists'),
                ...auto.map((p) => _PlaylistCard(playlist: p)),
                const SizedBox(height: 20),
              ],
              if (manual.isNotEmpty) ...[
                _sectionHeader('My Playlists', '${manual.length} playlists'),
                ...manual.map((p) => _PlaylistCard(playlist: p)),
              ],
            ],
          );
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        backgroundColor: AppTheme.accent,
        onPressed: () => _showCreatePlaylist(context),
        icon: const Icon(Icons.add_rounded, color: Colors.white),
        label:
            const Text('New Playlist', style: TextStyle(color: Colors.white)),
      ),
    );
  }

  Widget _sectionHeader(String title, String subtitle) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Row(
        children: [
          Text(title,
              style: const TextStyle(
                  color: AppTheme.textSecondary,
                  fontSize: 11,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 1.2)),
          const SizedBox(width: 8),
          Text('• $subtitle',
              style: const TextStyle(
                  color: AppTheme.textSecondary, fontSize: 11)),
        ],
      ),
    );
  }

  Widget _buildEmptyState(BuildContext context, MusicProvider provider) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 80,
              height: 80,
              decoration: BoxDecoration(
                gradient: AppTheme.accentGradient,
                shape: BoxShape.circle,
              ),
              child: const Icon(Icons.queue_music_rounded,
                  size: 40, color: Colors.white),
            ),
            const SizedBox(height: 16),
            const Text('No Playlists Yet',
                style: TextStyle(
                    color: AppTheme.textPrimary,
                    fontSize: 20,
                    fontWeight: FontWeight.w700)),
            const SizedBox(height: 8),
            const Text(
              'Create a playlist or generate\nsmart ones based on your mood tags',
              style: TextStyle(color: AppTheme.textSecondary, fontSize: 14),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.accentTertiary,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(
                    horizontal: 20, vertical: 12),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12)),
              ),
              onPressed: () async {
                await provider.generateAutoPlaylists();
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('Smart playlists generated!'),
                      backgroundColor: AppTheme.accentTertiary,
                      behavior: SnackBarBehavior.floating,
                    ),
                  );
                }
              },
              icon: const Icon(Icons.auto_fix_high_rounded),
              label: const Text('Generate Smart Playlists'),
            ),
          ],
        ),
      ),
    );
  }

  void _showCreatePlaylist(BuildContext context) {
    final ctrl = TextEditingController();
    final descCtrl = TextEditingController();
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surfaceDark,
        title: const Text('New Playlist'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: ctrl,
              style: const TextStyle(color: AppTheme.textPrimary),
              autofocus: true,
              decoration: const InputDecoration(
                hintText: 'Playlist name',
                prefixIcon: Icon(Icons.queue_music_rounded, size: 18),
              ),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: descCtrl,
              style: const TextStyle(color: AppTheme.textPrimary),
              decoration: const InputDecoration(
                hintText: 'Description (optional)',
                prefixIcon: Icon(Icons.notes_rounded, size: 18),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel',
                style: TextStyle(color: AppTheme.textSecondary)),
          ),
          ElevatedButton(
            style:
                ElevatedButton.styleFrom(backgroundColor: AppTheme.accent),
            onPressed: () async {
              final name = ctrl.text.trim();
              if (name.isNotEmpty) {
                await context.read<MusicProvider>().createPlaylist(
                      name,
                      description: descCtrl.text.trim().isEmpty
                          ? null
                          : descCtrl.text.trim(),
                    );
                if (ctx.mounted) Navigator.pop(ctx);
              }
            },
            child:
                const Text('Create', style: TextStyle(color: Colors.white)),
          ),
        ],
      ),
    );
  }
}

class _PlaylistCard extends StatelessWidget {
  final Playlist playlist;
  const _PlaylistCard({required this.playlist});

  @override
  Widget build(BuildContext context) {
    final isAuto = playlist.isAutoGenerated;
    return Card(
      color: AppTheme.cardDark,
      margin: const EdgeInsets.only(bottom: 10),
      shape:
          RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      child: InkWell(
        borderRadius: BorderRadius.circular(14),
        onTap: () => Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => PlaylistDetailScreen(playlistId: playlist.id!),
          ),
        ),
        child: Padding(
          padding: const EdgeInsets.all(14),
          child: Row(
            children: [
              Container(
                width: 52,
                height: 52,
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: isAuto
                        ? [AppTheme.accentTertiary, AppTheme.accent]
                        : [AppTheme.accent, AppTheme.accentSecondary],
                  ),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(
                  isAuto
                      ? Icons.auto_awesome_rounded
                      : Icons.queue_music_rounded,
                  color: Colors.white,
                  size: 26,
                ),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(playlist.name,
                        style: const TextStyle(
                            color: AppTheme.textPrimary,
                            fontSize: 14,
                            fontWeight: FontWeight.w600)),
                    const SizedBox(height: 3),
                    Text(
                      '${playlist.songCount}  •  ${playlist.formattedDuration}',
                      style: const TextStyle(
                          color: AppTheme.textSecondary, fontSize: 12),
                    ),
                    if (playlist.description != null) ...[
                      const SizedBox(height: 2),
                      Text(playlist.description!,
                          style: const TextStyle(
                              color: AppTheme.textSecondary, fontSize: 11),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis),
                    ],
                  ],
                ),
              ),
              IconButton(
                icon: const Icon(Icons.play_circle_filled_rounded,
                    color: AppTheme.accent, size: 38),
                onPressed: playlist.songs.isEmpty
                    ? null
                    : () {
                        context
                            .read<MusicProvider>()
                            .playPlaylist(playlist);
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                              builder: (_) => const NowPlayingScreen()),
                        );
                      },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// BUG FIX: uses playlistId instead of the playlist object to always fetch fresh data
class PlaylistDetailScreen extends StatelessWidget {
  final int playlistId;
  const PlaylistDetailScreen({super.key, required this.playlistId});

  @override
  Widget build(BuildContext context) {
    return Consumer<MusicProvider>(
      builder: (context, provider, _) {
        // BUG FIX: safe lookup with orElse to prevent StateError
        final playlist = provider.playlists.cast<Playlist?>().firstWhere(
              (p) => p?.id == playlistId,
              orElse: () => null,
            );

        if (playlist == null) {
          return Scaffold(
            backgroundColor: AppTheme.primaryDark,
            appBar: AppBar(title: const Text('Playlist')),
            body: const Center(
                child: Text('Playlist not found',
                    style: TextStyle(color: AppTheme.textSecondary))),
          );
        }

        return Scaffold(
          backgroundColor: AppTheme.primaryDark,
          appBar: AppBar(
            title: Text(playlist.name),
            actions: [
              if (!playlist.isAutoGenerated)
                IconButton(
                  icon: const Icon(Icons.delete_outline_rounded,
                      color: Colors.redAccent),
                  onPressed: () => _confirmDelete(context, playlist, provider),
                ),
            ],
          ),
          body: Column(
            children: [
              _buildHeader(context, playlist, provider),
              Expanded(
                child: playlist.songs.isEmpty
                    ? const Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(Icons.queue_music_rounded,
                                color: AppTheme.textSecondary, size: 48),
                            SizedBox(height: 12),
                            Text('No songs in this playlist',
                                style: TextStyle(
                                    color: AppTheme.textSecondary,
                                    fontSize: 15)),
                            SizedBox(height: 6),
                            Text(
                              'Add songs from the library (⋮ menu)',
                              style: TextStyle(
                                  color: AppTheme.textSecondary,
                                  fontSize: 12),
                            ),
                          ],
                        ),
                      )
                    : ListView.builder(
                        padding: const EdgeInsets.only(bottom: 100),
                        itemCount: playlist.songs.length,
                        itemBuilder: (context, index) {
                          final song = playlist.songs[index];
                          final isPlaying =
                              provider.audioService.currentSong?.id ==
                                  song.id;
                          return SongTile(
                            song: song,
                            isPlaying: isPlaying,
                            onTap: () {
                              provider.audioService.setQueue(
                                  playlist.songs,
                                  startIndex: index);
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (_) =>
                                        const NowPlayingScreen()),
                              );
                            },
                            onFavorite: () =>
                                provider.toggleFavorite(song),
                            onMore: playlist.isAutoGenerated
                                ? null
                                : () => _confirmRemoveSong(
                                    context, playlist, song, provider),
                          );
                        },
                      ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildHeader(BuildContext context, Playlist playlist,
      MusicProvider provider) {
    final isAuto = playlist.isAutoGenerated;
    return Container(
      margin: const EdgeInsets.all(16),
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: isAuto
              ? [AppTheme.accentTertiary.withOpacity(0.25), AppTheme.cardDark]
              : [AppTheme.accent.withOpacity(0.25), AppTheme.cardDark],
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isAuto
              ? AppTheme.accentTertiary.withOpacity(0.2)
              : AppTheme.accent.withOpacity(0.2),
        ),
      ),
      child: Row(
        children: [
          Container(
            width: 60,
            height: 60,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: isAuto
                    ? [AppTheme.accentTertiary, AppTheme.accent]
                    : [AppTheme.accent, AppTheme.accentSecondary],
              ),
              borderRadius: BorderRadius.circular(14),
            ),
            child: Icon(
              isAuto
                  ? Icons.auto_awesome_rounded
                  : Icons.queue_music_rounded,
              color: Colors.white,
              size: 30,
            ),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(playlist.name,
                    style: const TextStyle(
                        color: Colors.white,
                        fontSize: 17,
                        fontWeight: FontWeight.w700)),
                const SizedBox(height: 2),
                Text(
                  '${playlist.songCount}  •  ${playlist.formattedDuration}',
                  style: const TextStyle(
                      color: AppTheme.textSecondary, fontSize: 13),
                ),
                if (playlist.description != null)
                  Text(playlist.description!,
                      style: const TextStyle(
                          color: AppTheme.textSecondary, fontSize: 11)),
              ],
            ),
          ),
          if (playlist.songs.isNotEmpty)
            ElevatedButton.icon(
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.accent,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(
                    horizontal: 14, vertical: 10),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10)),
              ),
              onPressed: () {
                provider.playPlaylist(playlist);
                Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (_) => const NowPlayingScreen()),
                );
              },
              icon: const Icon(Icons.play_arrow_rounded, size: 18),
              label: const Text('Play'),
            ),
        ],
      ),
    );
  }

  void _confirmDelete(BuildContext context, Playlist playlist,
      MusicProvider provider) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surfaceDark,
        title: const Text('Delete Playlist'),
        content: Text('Delete "${playlist.name}"? Songs will not be removed.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel',
                style: TextStyle(color: AppTheme.textSecondary)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                backgroundColor: Colors.redAccent),
            onPressed: () {
              Navigator.pop(ctx);
              provider.deletePlaylist(playlist.id!);
              Navigator.pop(context);
            },
            child: const Text('Delete',
                style: TextStyle(color: Colors.white)),
          ),
        ],
      ),
    );
  }

  void _confirmRemoveSong(BuildContext context, Playlist playlist,
      Song song, MusicProvider provider) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surfaceDark,
        title: const Text('Remove Song'),
        content:
            Text('Remove "${song.title}" from "${playlist.name}"?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel',
                style: TextStyle(color: AppTheme.textSecondary)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                backgroundColor: Colors.redAccent),
            onPressed: () {
              Navigator.pop(ctx);
              provider.removeSongFromPlaylist(playlist.id!, song.id!);
            },
            child: const Text('Remove',
                style: TextStyle(color: Colors.white)),
          ),
        ],
      ),
    );
  }
}
